### ISSUE TITLE
elm-package install doesn't seem to do anything

### ISSUE THREAD

**Issue by Aeolun** [emanchado/narrows#1]
Apparently that's caused by one of the libraries being unavailable at the version specified, but I have no idea what to update to make it work.

**Comment by Aeolun** [comment]
Never mind, it's a bug in elm itself. If there's a 'elm-stuff' directory already existing it won't install anything.

**Comment by emanchado** [comment]
That was quick and painless :-) If you get it to run it and use it, please provide some feedback (just open a new issue or whatever)!
