### ISSUE TITLE
Brunch Build Error

### ISSUE THREAD

**Issue by hlopez058** [emanchado/narrows#3]
Hello, I am having trouble trying to install it on my system could you help me figure it out?
I have the latest NPM installed. Is there something wrong with the latest release?

Trying to run the "buildfe" using :
`npm run buildfe`

The `brunch build` failed at the `npm install` line.

> 
> Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "buildfe"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! narrows@0.0.1 buildfe: `brunch build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the narrows@0.0.1 buildfe script 'brunch build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the narrows package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     brunch build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs narrows
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls narrows
> npm ERR! There is likely additional logging output above.

[Uploading 2017-05-28T02_25_44_827Z-debug.txt…]()

**Comment by emanchado** [comment]
Hi!

I have tried upgrading to NPM 7.10 and rebuild `node_modules` and such, and I cannot reproduce the error :-( I wonder if it's a problem with Windows...

The previous step, `elm-package install`, worked fine? Did you get any errors or warnings before trying to run `npm run buildfe`?

**Comment by johnpaulada** [comment]
I'm also encountering this problem. I just updated my Node and npm. I'll let you know how it goes. I'm on macOS Sierra btw.

**Comment by johnpaulada** [comment]
Got the same error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'buildfe' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuildfe', 'buildfe', 'postbuildfe' ]
5 info lifecycle narrows@0.0.1~prebuildfe: narrows@0.0.1
6 silly lifecycle narrows@0.0.1~prebuildfe: no script for prebuildfe, continuing
7 info lifecycle narrows@0.0.1~buildfe: narrows@0.0.1
8 verbose lifecycle narrows@0.0.1~buildfe: unsafe-perm in lifecycle true
9 verbose lifecycle narrows@0.0.1~buildfe: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/johnpaulada/Desktop/projects/narrows/node_modules/.bin:/Users/johnpaulada/.fastlane/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/johnpaulada/Library/Android/sdk/tools:/Users/johnpaulada/Library/Android/sdk/platform-tools:/Users/johnpaulada/.composer/vendor/bin:/usr/local/opt/go/libexec/bin
10 verbose lifecycle narrows@0.0.1~buildfe: CWD: /Users/johnpaulada/Desktop/projects/narrows
11 silly lifecycle narrows@0.0.1~buildfe: Args: [ '-c', 'brunch build' ]
12 silly lifecycle narrows@0.0.1~buildfe: Returned: code: 1  signal: null
13 info lifecycle narrows@0.0.1~buildfe: Failed to exec buildfe script
14 verbose stack Error: narrows@0.0.1 buildfe: `brunch build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid narrows@0.0.1
16 verbose cwd /Users/johnpaulada/Desktop/projects/narrows
17 error Darwin 16.1.0
18 error argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "buildfe"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error narrows@0.0.1 buildfe: `brunch build`
23 error Exit status 1
24 error Failed at the narrows@0.0.1 buildfe script 'brunch build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the narrows package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     brunch build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs narrows
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls narrows
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by emanchado** [comment]
Hey, thanks for the extra information! I really wonder what's different on my machine :-S But it's obviously not a Windows-specific issue.

Let's see, can you run `node_modules/.bin/brunch`? Is the command there? Does it run at all? If so, can you try `node_modules/.bin/brunch build`? Also, see the other question above: can you successfully run `elm-package install`? No weird output or warnings?

**Comment by hlopez058** [comment]
@emanchado , The ELM packages where installed and configured successfully.
I tried running brunch build as 'node_modules/.bin/brunch build' , I get the same error. 
I am running on Windows 10 x64.

**Comment by emanchado** [comment]
I don't have access to a Windows 10 machine :-( I will try and remember to test in an older Windows machine I have lying around.

When you say "the same error", do you mean the lines marked "14"? Because the rest is generated by npm, right?

Is the file `node_modules/.bin/brunch` even there? What happens when you run without the `build` at the end, same error again? If so, it seems that brunch doesn't work at all in your machine for some reason...

**Comment by hlopez058** [comment]
The 'node_modules/.bin/brunch'  command is there. when I run the build it failed. i moved over the packages and config file then ran it again. I got the following :

Is there another way to deploy it ? 

Its a great idea, i was trying to do something similar a while back. 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN narrows@0.0.1 No repository field.
npm WARN narrows@0.0.1 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

```
[Uploading 2017-05-28T19_56_42_873Z-debug.txt…]()

**Comment by johnpaulada** [comment]
I tried `./node_modules/.bin/brunch build.
Here's the output:
```
10:27:19 - info: compiling
Elm compile: app/Main.elm, to public/compiled/js/main.js
elm-make: elm-stuff/packages/Bogdanp/elm-combine/3.1.1/elm-package.json: openBinaryFile: does not exist (No such file or directory)
10:27:23 - info: compiling.
10:27:25 - error: Compiling of app/Main.elm failed. Error: Command failed: elm make --yes --warn --output public/compiled/js/main.js app/Main.elm
   elm-make: elm-stuff/packages/Bogdanp/elm-combine/3.1.1/elm-package.json: openBinaryFile: does not exist (No such file or directory)
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
10:27:26 - info: compiled 50 files into ports.bundle.js in 27.2 sec
```

**Comment by emanchado** [comment]
Now *that's* an interesting error message. I do have `elm-stuff/packages/Bogdanp/elm-combine/3.1.1/elm-package.json`, and I can see that `Bogdanp/elm-combine` is in the dependencies when I run `elm-package install`. I wonder why you don't have it.

Can you wipe `elm-stuff`, run `elm-package install` again, and paste the output? Mine looks like this:

```esteban@hastur(master): ~/src/narrows$ elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    Bogdanp/elm-combine 3.1.1
    Bogdanp/elm-time 1.4.0
    elm-lang/core 5.1.1
    elm-lang/dom 1.1.1
    elm-lang/html 2.0.0
    elm-lang/http 1.0.0
    elm-lang/lazy 2.0.0
    elm-lang/navigation 2.1.0
    elm-lang/virtual-dom 2.0.4
    evancz/url-parser 2.0.1

Do you approve of this plan? [Y/n] 
Starting downloads...

  ● Bogdanp/elm-combine 3.1.1
  ● Bogdanp/elm-time 1.4.0
  ● elm-lang/core 5.1.1
  ● elm-lang/dom 1.1.1
  ● elm-lang/html 2.0.0
  ● elm-lang/http 1.0.0
  ● elm-lang/lazy 2.0.0
  ● elm-lang/navigation 2.1.0
  ● elm-lang/virtual-dom 2.0.4
  ● evancz/url-parser 2.0.1

Packages configured successfully!
```
Note how `Bogdanp/elm-combine` is there (in version `3.1.1`) and it's reported to be installed successfully.

**Comment by johnpaulada** [comment]
Oh damn. That worked.

**Comment by johnpaulada** [comment]
Let me try it out again and see if I can make it work from the beginning. 😄

**Comment by johnpaulada** [comment]
Tried this on a Docker image. Gives me this after install:
```
npm info ok 
Error: You are using Elm 0.18.0, but this project is saying it needs a version
in this range: 0.17.0 <= v < 0.18.0

This means this package has not been upgraded for the newer version of Elm yet.
Check out the upgrade docs for guidance on how to get things working again:
<https://github.com/elm-lang/elm-platform/tree/master/upgrade-docs>
```

**Comment by emanchado** [comment]
I don't understand how that is possible. [`elm-package.json`](https://github.com/emanchado/narrows/blob/master/elm-package.json) clearly has a `0.18.0 <= v < 0.19.0` in there. 0.18 is the correct version.

Are you using an updated `master`? In any case I made the upgrade to Elm 0.18 before I ever published the repo, but...

**Comment by johnpaulada** [comment]
Yeah I just cloned it.

**Comment by Synesso** [comment]
Issue replicated with this Dockerfile:

```
FROM buildpack-deps:jessie-scm

RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y \
  build-essential \
  nodejs

RUN git clone https://github.com/emanchado/narrows.git
WORKDIR /narrows
RUN npm install
RUN npm install -g elm@0.18
RUN elm-package install
RUN npm run buildfe
RUN npm run buildbe
```

**Comment by emanchado** [comment]
OK, I *think* I have figured it out. It seems that adding `elm-stuff/exact-dependencies.json` was a terrible idea. It seemingly makes `elm-package` think that those packages are *already* installed (I thought it would be like having `npm-shinkwrap.json`).

Can you please pull the latest commit and try again? And sorry for the trouble, I had never had anything written in Elm used by other people!

**Comment by Synesso** [comment]
That fixes the build issue for me. Thanks @emanchado

**Comment by emanchado** [comment]
@hlopez058: can you confirm it works for you and close the issue if so?

**Comment by johnpaulada** [comment]
Hi! It still breaks for me. Same error:
```
Error: You are using Elm 0.18.0, but this project is saying it needs a version
in this range: 0.17.0 <= v < 0.18.0

This means this package has not been upgraded for the newer version of Elm yet.
Check out the upgrade docs for guidance on how to get things working again:
<https://github.com/elm-lang/elm-platform/tree/master/upgrade-docs>
```

**Comment by johnpaulada** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/8457470/26615282/48511f20-45f8-11e7-936a-fcccdaf5074e.png)

**Comment by Synesso** [comment]
Do you mind sharing your Dockerfile @johnpaulada ?

**Comment by johnpaulada** [comment]
It works now but it gives me a `/bin/sh: 1: db-migrate: not found`.
Here's my Dockerfile:
```
FROM node:latest
RUN git clone https://github.com/emanchado/narrows.git /var/www/project
COPY ./setup.sh /var/www/project/
WORKDIR /var/www/project
EXPOSE 8000
RUN apt-get update -y
RUN apt-get install -y build-essential
RUN npm install
RUN npm install -g elm@0.18
RUN elm-package install --yes
RUN npm run buildfe
RUN npm run buildbe
RUN /bin/bash ./setup.sh
RUN apt-get install mysql-server -y
RUN service mysql start && mysql -uroot -proot -e "CREATE DATABASE narrows;"
RUN db-migrate up
RUN NODE_ENV=production node build/index.js
```

**Comment by emanchado** [comment]
Gah, my bad. I forget that most people don't have `node_modules/.bin` in their `$PATH` so they cannot call these commands directly.

I have added an NPM script and updated the installation instructions. You have to call `npm run dbmigrate` instead of `db-migrate up`.

Note that you will probably need to create `config/local-production.js` and tweak it. The application might not work with the defaults (in particular, the MySQL credentials).

If it works, I will assume that the Elm version problem is unrelated, and move it to a new issue.

**Comment by johnpaulada** [comment]
I tried `node_modules/.bin/db-migrate up` and it gave me this:
```
[ERROR] Error: Could not find database config file '/var/www/project/database.json'
    at Object.exports.loadFile (/var/www/project/node_modules/db-migrate/lib/config.js:46:11)
    at loadConfig (/var/www/project/node_modules/db-migrate/api.js:698:18)
    at dbmigrate (/var/www/project/node_modules/db-migrate/api.js:121:17)
    at Object.module.exports.getInstance (/var/www/project/node_modules/db-migrate/index.js:70:10)
    at /var/www/project/node_modules/db-migrate/bin/db-migrate:35:25
    at /var/www/project/node_modules/resolve/lib/async.js:45:21
    at ondir (/var/www/project/node_modules/resolve/lib/async.js:196:27)
    at onex (/var/www/project/node_modules/resolve/lib/async.js:104:32)
    at /var/www/project/node_modules/resolve/lib/async.js:24:24
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by emanchado** [comment]
_Sigh_. Missing installation step: you have to create a `database.json` file from the now-provided `database-sample.json` (configuration has to match your `config/local-production.js`, of course).

It really annoys me that the database credentials are duplicated. I'll try to find a way around it but I need some time to think about it. So, for now, you'll have to create `database.json`.

**Comment by emanchado** [comment]
On second thought, can you try with the new `migration-fixes` branch instead? You don't need to create `database.json` by hand, but you need to change the `npm run dbmigrate` command to:
```
NODE_ENV=production npm run dbmigrate
```
If you confirm it works, I'll merge that branch into `master`.

**Comment by johnpaulada** [comment]
It works.

**Comment by emanchado** [comment]
@johnpaulada: Excellent! Thanks for keeping at it, and sorry again for the bumpy road :-)

@hlopez058: Can you please confirm that it works for you with the updated version and updated instructions? You can close the task yourself.

**Comment by hlopez058** [comment]
I got failures in my `npm gyp rebuild` step. because gyp uses python less than 3 , so I installed python 2.7 set my python env variable and I was able to run the npm gyp successfully and get past the first step.
