### ISSUE TITLE
Docker launch fails:  ER_HOST_NOT_PRIVILEGED: Host 'XX.XX.XX.XX' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by wychwitch** [emanchado/narrows#32]
Hello!! I just discovered this app and it's a dream come true that I didn't know I had! I saw there were docker instructions, but when I tried running them I received the above error. I'm not sure why?

I edited the docker-compose.yml values, and then continued to created an .env file to assign the variables such as `PUBLIC_ADDRESS` and `NODEMAILER` as listed in the instructions. Am I missing something?

Also as a side note, I'm willing to try to install this outside of docker, but I'm not sure where to change the NODEMAILER variable? I use an SMTP and would like to send email via that if possible

Thank you again for making this wonderful webapp!! I've told a friend about it and we're both excited to give this a try.

**Comment by wychwitch** [comment]
I will say that I HAVE gotten it working flawlessly (so far, I haven't tested email yet I THINK I got that fixed) outside of docker! I'm incredibly excited

I won't close it because the docker issue still exists, I'm happy to try any debugging you'd like me to!

**Comment by JamyGolden** [comment]
The author passed away several weeks ago :cry: Such an amazing project he built for everyone.

**Comment by wychwitch** [comment]
> The author passed away several weeks ago 😢 Such an amazing project he built for everyone.

Holy fuck what;; I'm so sorry to hear that holy shit. You're right this was an amazing project he left for us. I hope the community can keep this part of his legacy going.
