### ISSUE TITLE
Database connections are not reset when the database disconnects temporarily

### ISSUE THREAD

**Issue by tessgadwa** [emanchado/narrows#6]
Upon successful login to a Narrows instance, previously saved stories failed to load.

![screen shot 2017-07-30 at 5 13 43 pm](https://user-images.githubusercontent.com/6475035/28757237-2c8f49b4-754c-11e7-813b-453cd3cd7c64.png)
![screen shot 2017-07-30 at 5 13 03 pm](https://user-images.githubusercontent.com/6475035/28757236-2c8eb2a6-754c-11e7-94b0-b3b8e994ea10.png)

**Comment by emanchado** [comment]
Does it happen still? If it doesn't, I think I know what the problem is (the code is not resetting the connection when the database goes down and up again, eg. after a database upgrade).

**Comment by tessgadwa** [comment]
Everything's back,  thanks.

On Jul 31, 2017 1:19 AM, "Esteban Manchado Velázquez" <
notifications@github.com> wrote:

Does it happen still? If it doesn't, I think I know what the problem is
(the code is not resetting the connection when the database goes down and
up again, eg. after a database upgrade).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/emanchado/narrows/issues/6#issuecomment-318970267>, or mute
the thread

**Comment by emanchado** [comment]
I think I have a solution for it. I'm testing a bit more locally, then I'll push the code. Thanks again for the report!
